apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-master
  labels:
    app: ingress-master
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ingress-dflt"
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
    - http:
        paths:
        - path: /branch_pizza
          pathType: ImplementationSpecific
          backend:
            service:
              name: newapp
              port: 
                number: 8080
        - path: /branch_soup
          pathType: ImplementationSpecific
          backend:
            service:
              name: newapp2
              port: 
                number: 80