apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
spec:
  selector:
    matchLabels:
      app: first-app
  replicas: 2
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
      - name: node-probe
        image: node-probe:latest
        startupProbe:
          httpGet:
            path: /api/healthcheck
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 3
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-db-secret
              key: DB_PASSWORD_DEV
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: my-db-secret
              key: DB_USER_DEV
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: my-db-secret
              key: DB_NAME_DEV
#   requests:
#     cpu: 50m
#     memory: 75Mi
#   limits:
#     cpu: 100m
#     memory: 150Mi

---
apiVersion: v1
kind: Service
metadata:
  name: node-probe-service
spec:
  selector:
    app: first-app
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
    nodePort: 32000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-lb
spec:
  selector:
    app: postgresql-db
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
      - name: postgresql-db
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresql-db-disk
          mountPath: /data
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-db-secret
              key: DB_PASSWORD_DEV
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: my-db-secret
              key: DB_USER_DEV
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: my-db-secret
              key: DB_NAME_DEV
  volumeClaimTemplates:
  - metadata:
      name: postgresql-db-disk
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
