apiVersion: apps/v1
kind: Deployment
metadata:
  name: newapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newapp
  template:
    metadata:
      labels:
        app: newapp
    spec:
      containers:
      - name: echoserver
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
---


apiVersion: v1
kind: Service
metadata:
  name: newapp
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: newapp
  type: NodePort
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: newapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newapp2
  template:
    metadata:
      labels:
        app: newapp2
    spec:
      containers:
      - name: superserver
        image: rancher/hello-world
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
---


apiVersion: v1
kind: Service
metadata:
  name: newapp2
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: newapp2
  type: NodePort
---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-master
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ingress-dflt"
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
    - http:
        paths:
        - path: /branch_pizza
          pathType: ImplementationSpecific
          backend:
            service:
              name: newapp
              port: 
                number: 8080
        - path: /branch_soup
          pathType: ImplementationSpecific
          backend:
            service:
              name: newapp2
              port: 
                number: 80              